version: '3.9'

services:
  go-api:
    container_name: go-banking-api
    image: mrcruz117/go-banking-api
    build: .
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: 'go-bank-db'
      DB_PORT: "5432"
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 8088:8088
    depends_on:
      - go-bank-db
  go-bank-db:
    container_name: go-bank-db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'go-bank'
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
